[package]
name = "sillypass-gtk"
version = "0.0.0"
edition = "2021"

[dependencies]
gtk = { version = "0.9.0", package = "gtk4", features = ["v4_14"] }
sillypass-lib = { path = "../sillypass-lib", features = ["client"] }
