[package]
name = "sillypass-lib"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
keepass = { version = "0.7.13", features = ["save_kdbx4"] }
reqwest = { version = "0.12.5", features = ["stream"] }

[features]
client = []
server = []
